version: "2.1"

volumes:

  home:
    driver: local

services:

  kuberdp-devdesktop:
    container_name: kuberdp-devdesktop
    hostname: kuberdp-devdesktop
    image: ${DESKTOP_IMAGE}
    privileged: true
    build: .
    ports:
    - "3389:3389"
    volumes:
    - "home:/home"
    environment:
      RDP_USERNAME: ${RDP_USERNAME}
      RDP_PASSWORD: ${RDP_PASSWORD}

