version: "2.1"

volumes:

  home:
    driver: local

services:

  kuberdp-spawner:
    container_name: kuberdp-spawner
    hostname: kuberdp-spawner
    image: ${SPAWNER_IMAGE}
    build: .
    privileged: true
    ports:
    - "3389:3389"
    environment:
      PORT: 3389
    environment:
      RDP_USERNAME: ${RDP_USERNAME}
      RDP_PASSWORD: ${RDP_PASSWORD}

